### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by skeetn1** [e-sim-python/scripts#11]
how can i run it with discord bot

**Comment by skeetn1** [comment]
cmd command (pip install discord.py) fix

**Comment by skeetn1** [comment]
https://prnt.sc/wlm71d

**Comment by Random-guy-on-internet** [comment]
Hello.
Well, i assume you already installed the required packages with pip in CMD.

Here is some troubleshooting steps:
1. Make sure the name of channel that you run your commands in is the same as the server you want to use, 
For Example: if you want to use `.work` command for `aura server`, **name of discord channel** should be `aura` and u should use command in that channel.
2. always check your bot token and make sure its valid.
3. check closed issues here, maybe someone already had the same problem as you did: [CLOSED ISSUES](https://github.com/e-sim-python/scripts/issues?q=is%3Aissue+is%3Aclosed)

Let me know how it goes and if you had any other issues, feel free to ask.

**Comment by skeetn1** [comment]
thanks
