### ISSUE TITLE
auto_fight script stopped working

### ISSUE THREAD

**Issue by randome-sim** [e-sim-python/scripts#12]
auto_fight script stopped working, about 2 days ago, thinking it's new change made in-game code

python script opens normally and you set numbers like normal you press enter to activate the script and it starts to looks for a battle then when it starts hitting and hitting command shows in a loop, like...

hit 1
hit 2
hit 3
hit 4

and continues to unlimited "without real hits in battle"

Please fix.

**Comment by e-sim-python** [comment]
Hey @randome-sim , thanks for noticing us.

auto-fight is now adjusted to the new in-game code.

We will take a deeper look into it soon and fix more things.

**Comment by randome-sim** [comment]
@e-sim-python Thanks for response, now auto_fight script works if you give it battle ID, Hits normal game.

but if you don't write battle ID number in (optional) line, it don't search for battle automatically like before.

picture https://prnt.sc/10glsqu

**Comment by e-sim-python** [comment]
@randome-sim Thanks to your screenshot i was able to find the problem.
You can download the last version of [Help_functions/bot_functions.py](https://github.com/e-sim-python/scripts/blob/master/Help_functions/bot_functions.py) now.

**Comment by randome-sim** [comment]
@e-sim-python Thanks for the quick response, It's working now :)

Will report any new issues and updates in code again, but this issue is closed now thank you :)
