### ISSUE TITLE
iOS Users

### ISSUE THREAD

**Issue by Autowinner** [e-sim-python/scripts#15]
I would like to know if there is any way to use for cell phones with ios?

**Comment by Random-guy-on-internet** [comment]
Hi.
There is an app for iOS called [pyto](https://pyto.app/), however, I don't have an iPhone to run tests on it and give you the information you need to be able to run it straight forward.
But I will give you some starting points, maybe you will be able to do it on your own.
first, install Pyto.
then download the script files from here: 
[link to code](https://github.com/e-sim-python/scripts/tree/Requests) and [download link](https://github.com/e-sim-python/scripts/archive/Requests.zip)
after downloading them, you unzip the file you downloaded into your phone storage.
**1.open the Pyto app**, and **2.** navigate to the folder that you just unzipped scripts into it, **3.** find the `auto-fight.py` file in `Fight` folder.
**4.** open it and click on the run button in Pyto app.

this is as far as I can help you rn, let me know how it goes.
