### ISSUE TITLE
dead ?

### ISSUE THREAD

**Issue by Autowinner** [e-sim-python/scripts#18]
Script dead ??

**Comment by e-sim-python** [comment]
Hello there.
It works perfectly fine for me, maybe you just have to [download the new version](https://github.com/e-sim-python/scripts/archive/refs/heads/master.zip) (we have made some critical changes recently).

If it didn't solve your problem, can you be more specific with the problem you are dealing with?

**Comment by pupini** [comment]
hi script its not working hits first regens perfectly but in second time to hits regens freeze write the battle link ths side ull hit and frezze not hitting anymore then appears error:   and go to sleep for xxx seconds  like this:
Logged successfully
Hit 0
Hit 1
Sleeping for 850.0 seconds.
https://aura.e-sim.org/battle.html?id=9320 side: attacker
error:
Sleeping for 677.0 seconds.
btw u r doing a great job
