### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by pupini** [e-sim-python/scripts#19]
hi script its not working hits first regens perfectly but in second time to hits regens freeze write the battle link ths side ull hit and frezze not hitting anymore then appears error: and go to sleep for xxx seconds like this:
Logged successfully
Hit 0
Hit 1
Sleeping for 850.0 seconds.
https://aura.e-sim.org/battle.html?id=9320 side: attacker
error:
Sleeping for 677.0 seconds.
btw u r doing a great job

**Comment by Random-guy-on-internet** [comment]
Hi @pupini, thanks for reporting the issue.

I have tested it for a few restores and it was working fine, however, I made some changes in the code, hopefully, it will fix it.

Download the codes again, It'll be fixed!

**Comment by pupini** [comment]
still not working here s what script do
btw it works on suna perm
Logged successfully
Hit 1
Hit 2
Hit 3
Sleeping for 657.0 seconds.
https://exura.e-sim.org/battle.html?id=2379 side: attacker
error:
Sleeping for 457.0 seconds.
https://exura.e-sim.org/battle.html?id=2379 side: attacker
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\miroslav\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\miroslav\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
OSError: [WinError 10038] Se intentó realizar una operación en un elemento que no es un socket
Hit 1
Hit 2
Hit 3
Sleeping for 255.0 seconds.
https://exura.e-sim.org/battle.html?id=2379 side: attacker
error:
Sleeping for 252.0 seconds.

**Comment by Random-guy-on-internet** [comment]
okay, then the problem is on your side.
here is what I suggest you to do:
1. first uninstall your python program, restart your pc.
2. then install the 32bit version of python, download [suggested version](https://www.python.org/ftp/python/3.8.8/python-3.8.8.exe)
**1. don't forget to follow instructions again step by step.**
**2. remember to restart your pc after installing 32bit version of python, then proceed to install packages (`pip install ...`)**

3. make sure you have a stable connection, don't use free proxies/VPN, they usually log your information and you get `connection not secure` errors.


If the problem presists, try running the scripts with a different internet connection.

**Comment by pupini** [comment]
hi again i try everything u said and it works perfectly on my permanent server suna but in exura which is a temporary server dint worked it hits only one hit 1 time  and error appears

**Comment by Random-guy-on-internet** [comment]
Hi, sorry to hear that.

here is a modified version of the scripts:

[click here to download modified login.zip file](https://github.com/e-sim-python/scripts/files/6215546/login.zip)

Download the zip file, extract the `login.py` file from the zip file, and copy it to this location in your scripts folder.

location to copy the new file : 

**your script folder > eSim > Help_function**  

![1](https://user-images.githubusercontent.com/66680456/112718927-b17f6980-8f13-11eb-8b09-58aab4ab9972.jpg)

there is another file with the same name in there, simply replace it with this one I gave u and give it a try.

let me know how it goes, my friend! 😉

**Comment by pupini** [comment]
now this happen still working good on suna server problem is with temp server:
 It will tell e-sim that you browsing through your regular browser, so make sure there are no mistakes
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
Logged successfully
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\miroslav\AppData\Local\Programs\Python\Python38-32\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\miroslav\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
OSError: [WinError 10038] Se intentó realizar una operación en un elemento que no es un socket
Hit 1
Hit 2
Sleeping for 702.0 seconds.
https://exura.e-sim.org/battle.html?id=2716 side: attacker
error:
Sleeping for 734.0 seconds.

**Comment by pupini** [comment]
now this happen but still working good un permanent server trouble is in exura:

It will tell e-sim that you browsing through your regular browser, so make sure there are no mistakes
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
Logged successfully
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\miroslav\AppData\Local\Programs\Python\Python38-32\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\miroslav\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
OSError: [WinError 10038] Se intentó realizar una operación en un elemento que no es un socket
Hit 1
Hit 2
Sleeping for 702.0 seconds.
https://exura.e-sim.org/battle.html?id=2716 side: attacker
error:
Sleeping for 734.0 seconds.

**Comment by Random-guy-on-internet** [comment]
Hi, I tested it again and everything works smoothly.

![Screenshot_1](https://user-images.githubusercontent.com/66680456/112749124-9412d400-8fd5-11eb-8f34-ebb11feb917a.jpg)

------
to find what's going on with your scripts, I added an error logger.
here is what you do:
1. download this file: [auto_fight.zip](https://github.com/e-sim-python/scripts/files/6217139/auto_fight.zip)
2. extract `auto_fight.py` file and paste it in this location: your script folder > eSim > Fight
3. then run the `auto_fight.py` script I gave u for your normal server, primera/secura/Suna/alpha for 3 restores ( only one server is enough), then do the same thing for exura.
4. send the log files to me here. log files are in the same folder as `auto_fight.py` file, and they are text files named based on the server u ran scripts on like `exura.txt`
log file will be like this:

![Screenshot_2](https://user-images.githubusercontent.com/66680456/112749532-12707580-8fd8-11eb-94ae-77e0882f83b5.jpg)

you can drag the file to here to upload it like so:

![Screenshot_4](https://user-images.githubusercontent.com/66680456/112749580-71ce8580-8fd8-11eb-86e5-bdd198ba196f.jpg)

**Comment by pupini** [comment]
[suna.txt](https://github.com/e-sim-python/scripts/files/6218586/suna.txt)
[exura.txt](https://github.com/e-sim-python/scripts/files/6218588/exura.txt)

**Comment by Random-guy-on-internet** [comment]
you have internet problems and that's the only reason you get errors.

there is nothing else that i can do for you.

also you can ignore this error, it doesnt have any impact on your scripts.

`OSError: [WinError 10038] Se intentَ realizar una operaciَn en un elemento que no es un socket`
