### ISSUE TITLE
First Time Running Issues

### ISSUE THREAD

**Issue by Aztu333** [e-sim-python/scripts#2]
I want to use the bot that hits in auto fight bot in alpha, I installed the program, what should I change in it?
https://prnt.sc/um9szf
https://prnt.sc/um9taw

**Comment by Random-guy-on-internet** [comment]
Hello @Aztu333!

1.first of all after opening the `auto_fight.py` file with **Right Click** and selecting **Edit with IDLE**, it will show the window that you posted on screenshot, you made it so far.

2.Next step will be running the script either with pressing F5 on keyboard or with-in IDLE window and choosing **Run Module** from **Run Menu** like this: [ScreenShot](https://prntscr.com/umdss6)
either of those will run the script, ( these 2 steps work for all of the scripts provided in this repository )
3.After running the Script, you simply answer the Questions asked, then it will run the autofight program.

If you run any script for the first time, program will ask for your information (server,username, password) and as it says, it will store them in **Help_functions folder** so you dont have to enter your credentials every time you want to run the scripts.

And when you run any script a second time, it will ask you what server you desire to run the script on so if you stored your alpha information already, just type your server name as **alpha** and it will automatically load your alpha information in program.

Happy scripting 👍

**Comment by Aztu333** [comment]
https://prnt.sc/umed8q

**Comment by e-sim-python** [comment]
Hello @Aztu333 !
As posted [here](https://github.com/e-sim-python/scripts#errors), you need to install the `requests` library.
To do so, you can either type in your start menu `pip install requests`, or run [install_packets.py](https://github.com/e-sim-python/scripts/blob/master/Help_functions/install_packets.py).
If you facing any errors, just [google it](https://www.google.com/search?q=python+install+requests)

Btw, you can also double click on the file you want, and it will run it (no need to edit with IDLE)

**Comment by Aztu333** [comment]
https://prnt.sc/umkqq4

**Comment by e-sim-python** [comment]
@Aztu333 
I have tested it again, and it works.

Check your details in `Help_functions` folder -> `login_details.csv` file.
Make sure you enter the name and password correctly (note uppercase/lowercase letters & spaces).
You can also delete the file, and the program will ask for your details again, in order to recreate the file.

(Also note that you don't have to write "0" for food and gift - just press Enter)

**Comment by Aztu333** [comment]
I managed to run it, but it asked me to get code from https://www.whatsmyua.info/, will it always ask?
automatic hit stops after the computer goes into sleep mode

**Comment by e-sim-python** [comment]
@Aztu333 It ask only 1 time about user-agent (it save it in your computer).
All the scripts works as long as you keep them open - so yeah, sleep mode will stop them.

You can, of course, disable sleep mode in your computer.

**Comment by Aztu333** [comment]
Is there an application to use on mobile?

**Comment by e-sim-python** [comment]
I have not checked, but there should be a Python app for android as well, and it should run fine on it.

**Comment by Aztu333** [comment]
Android I could not: /

**Comment by e-sim-python** [comment]
Can you describe the problem?

**Comment by Aztu333** [comment]
https://prnt.sc/umptpp
https://prnt.sc/umqnz8

**Comment by e-sim-python** [comment]
I updated [install_packets.py](https://github.com/e-sim-python/scripts/blob/master/Help_functions/install_packets.py) - it will try some others methods as well now.

**Comment by Aztu333** [comment]
auto_fight / https://prnt.sc/un0gg7

install_packets / https://prnt.sc/un0ivy
https://prnt.sc/un0kdz
https://prnt.sc/un0l0n
https://prnt.sc/un0ly2

login / https://prnt.sc/un0myu

App: Pydroid 3

I could not do it on the phone ;(

**Comment by Random-guy-on-internet** [comment]
@Aztu333 

to run scripts on android devices, do as i say :

1.Install **Pydroid 3 - IDE for Python 3** from Google Play Store. ( you did this one already )

2.Install **Pydroid repository plugin** from Google Play Store.

3.Open **Pydroid 3**, from top left side of app, click on menu, there are a few options, such as Get premium, interpreter, Terminal, etc,Now you should choose **Pip**.

4.In **Library name** field, first type **lxml** (its LXML not ixmi) and click on install, after its finished, enter **Requests** in that field and go ahead and click install. ( you can do this for any missing module in future if you needed it)

5.Now, just go back in main menu and click on folder icon in top right side of the app ( near light bulb icon ) and choose open, find your desired script in your phone file manager and open it.

6.Once you opened it, there should be a **Run yellowish play button** in left bottom of screen, go ahead and run it.

Good Luck.

**Comment by Aztu333** [comment]
I managed to start it but the phone does not auto fight when your screen turns off

**Comment by Random-guy-on-internet** [comment]
@Aztu333 excellent!

Now when you run the script in your phone, on top right side of the screen, there is a menu.

In that menu, choose **Take wakelock** and **Take wifilock**. [Screenshot](http://prntscr.com/uo9dxh)

Now it should be able to run as long as you don't close the app from your phone's app manager.

let me know if it solves your problem. o7
