### ISSUE TITLE
issue with automatic battle assign

### ISSUE THREAD

**Issue by randome-sim** [e-sim-python/scripts#20]
Hi, there's an issue with the automatic battle assignment in exura server.

it appears to be only on exura server so it must be new code change on the new temp.

https://prnt.sc/10z8ele

As you can see it won't automatically assign battle, script works ONLY if you provide battle ID, then even if the battle is over you'll get the script response in the picture above.

Hope that information helps the tweaking process!

**Comment by e-sim-python** [comment]
Hi @randome-sim , thanks for your report.
the `battles.html` page is now locked for non-players, but hopefully my last change will fix that.

**Comment by randome-sim** [comment]
@e-sim-python 

Now it works perfectly, Thank you!

will keep an eye for any upcoming changes as usual :)

This issue should be now considered closed.
