### ISSUE TITLE
auto fly>work

### ISSUE THREAD

**Issue by randome-sim** [e-sim-python/scripts#25]
Hi.

There's 1 little problem left that needs fixing.

when you have auto_fight fighting somewhere and it's time for you to work, The script says: successfully trained & worked and travelled back... while in reality it didn't.

this only works if you have Q5 Tickets. "It used to work with Q1 tickets before.

so, i already edited the script to default use q1 instead of q5, same as before, But in these newer script version it doesn't work sadly.

Waiting on ur answer and thanks for your time!

**Comment by e-sim-python** [comment]
Hi @randome-sim 
In double_click method, it try to fly with Q5 tickets, so the reason it didn't work is probably because you didn't have any.

anyway, i edited it to be Q1 tickets by default, hopefully it will solve it.

**Comment by randome-sim** [comment]
@e-sim-python 

now it doesn't work at all, also train stopped working it basically shows this...

I couldn't find in which region your work is. Maybe you don't have a job
https://alpha.e-sim.org/travel.html

then continue the auto_fight script without work or train xD

and each 1-2 hour it says the same when it tries to work again, and it doesn't fly anywhere.

**Comment by Random-guy-on-internet** [comment]
@randome-sim 
hi, there was a typo, download the codes again and give it a try.

**Comment by randome-sim** [comment]
Now it works perfect!

Thank you!
