### ISSUE TITLE
trouble with restors flying with q1 tickets

### ISSUE THREAD

**Issue by pupini** [e-sim-python/scripts#27]
i think there s is trouble flying with q1 tickes and using restores first restores goes ok an then  the others restores goes like this:
 traveling to a region
    =======================
    to Use Flight Set for drops, enter 2nd region.

    it will travel between 2 regions every 10 mins.(similar to auto_fight)
    if you decide to use limits, it will consume 1 Q5 food and 1 Q5 gift as well.
    
Server: aura
Ticket quality (1-5): 1
Region id: 722
2nd region id for flight set, otherwise press enter: 137
Using limits (y/n)? y
Logged successfully
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
Sleeping for 565.0 seconds.
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
https://aura.e-sim.org/travel.html
Sleeping for 1052.0 seconds.
it flies but u have to wait a lot and u lose some restores cause of this non flyng wheel

**Comment by Random-guy-on-internet** [comment]
@pupini Hi,
There was a typo before and I fixed it but I missed the other one, and now, it's resolved.
download the codes again, and give it a try.

thanks for reporting!

**Comment by shekemo** [comment]
How to to that if i travel have eqs?

**Comment by Random-guy-on-internet** [comment]
if you have travel equips, the only difference is that you won't use tickets.
