### ISSUE TITLE
creating "main" script

### ISSUE THREAD

**Issue by zazo14** [e-sim-python/scripts#3]
Hi! Do you have any plan to merge all the scripts into one "main" script? And then creating a queue of actions? i.e.: Do you want to run work script? Y/N - if Y add work script to queue and loop on 8 hours. Do you want to run train script? etc.

**Comment by zazo14** [comment]
```
def job(server, session=""):    
    URL = f"https://{server}.e-sim.org/"
    if not session:
        session = login(server)
    change_job = input("Do you want to leave your job and apply for the best offer at local market? Press y to leave job and n to stay at current one ")
    if change_job == "y":
        session.post(URL + "work.html", data={'action': "leave", "submit": "Submit"})
        jobMarket = session.get(URL + "jobMarket.html")
        tree = fromstring(jobMarket.content)
        jobId = tree.xpath("//tr[2]//td[6]//input[1]")[0].value
        apply = session.post(URL + "jobMarket.html", data={"id": jobId, "submit": "Apply"})
        print(apply.url)
    double_click(server, session=session)
    return session
```

changed the job module a bit, so you can decide if you want to change the job or stay at current one

**Comment by e-sim-python** [comment]
Nice change.
In my opinion, there are too many scripts, and it will become cumbersome if it merges into a single file, but you can of course do it yourself, depending on your needs.
However, there are plans to publish a bot for Discord, where you can control everything using commands.

**Comment by e-sim-python** [comment]
@zazo14 
Check this out -> https://github.com/e-sim-python/scripts/blob/master/bot.py
(First version)

**Comment by zazo14** [comment]
@e-sim-python 
Nice! But I'm getting error: No such file or directory: '../Help_functions/login_details.csv'

Not sure why though, the file is located where it should be.

**Comment by e-sim-python** [comment]
@zazo14 I will update login.py now
