### ISSUE TITLE
and

### ISSUE THREAD

**Issue by shekemo** [e-sim-python/scripts#30]
i dont know how to use  Buy currency.py Some toturial Me want to steal Npcs pls

**Comment by shekemo** [comment]
And Supply.py dint work

**Comment by Random-guy-on-internet** [comment]
Hi,
first of all, stop opening new issues, just send all in one issue ticket, and re-open old ones if it's closed.

-----

1. The league suggestion, we do not offer such a service, most of our scripts require **manual user inputs** and they do the extra boring work for users, like fighting every 10 mins, or bid in auctions for all specific equipment, and other repetitive tasks.
so if you are interested in more than what we offered, you should invest in learning coding or an easier way would be to hire a professional to do it for you

-------

2. for using [buy_cc](https://github.com/e-sim-python/scripts/blob/master/eSim/Basic/buy_cc.py) script, there is one thing you need to figure out on your own which is **Country id**, and to know that, there are a few ways:

    1. you just simply open the `Monetary Market` page in e-sim, select the currency you want to buy on the page, and click on view offers, then after the page is loaded, in the page address ( or otherwise known as URL, example: https://primera.e-sim.org/monetaryMarket.html?buyerCurrencyId=34&sellerCurrencyId=0 ), the number in front of **buyerCurrencyId** is the **Country id** ( in the example URL, **Country id** is 34 which is **Country id** for India )

    2. another way is using e-sim country API, here is the link to API: **https://primera.e-sim.org/apiCountries.html**, open the link for your desired server, open page search with `ctrl + f` key in your keyboard, and type the currency name you want to buy, `id` is written in front of it, [screenshot](https://i.imgur.com/BAcSXIi.jpg)

Here is a full example of buying 300 INR at the maximum price of 0.06g per INR in primera server using `buy_cc.py` script.

![1](https://user-images.githubusercontent.com/66680456/116328736-eadf1980-a7de-11eb-8526-3e368883814e.jpg)

------

3. to use `supply.py`, first of all your need to be in a mu and have storage access, from there it's as easy as doing something like this:
![Screenshot_2](https://user-images.githubusercontent.com/66680456/116329585-eca9dc80-a7e0-11eb-9097-d81720ba72ec.jpg)
