### ISSUE TITLE
Name 'session' is not defined

### ISSUE THREAD

**Issue by GeraltOfMurlocs** [e-sim-python/scripts#33]
Whenever i open up any of the scripts it tells me:

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020A3DE07A90>
error: name 'session' is not defined

But script works with bot. What is the problem and how can I fix it?

**Comment by Random-guy-on-internet** [comment]
Hi @GeraltOfMurlocs ,

Can you tell me the steps to reproduce the issue? with some screenshots if possible.
and answer as many questions as you can.

1. **which one/ones did u open that gives the error? (name of the file(s) )**
2. **what server did you try it on?**
3. how long does it take to get the error?
4. **did you download the latest version?**
> But script works with bot
5. do you mean auto-hit bot?
6. **did you move any files from the folders that they are in, to another folder?**
7. **Do you use PC, Android or iOS?**
------
i believe its some of the files you use that are malfunctioning/bugged but giving the extra info helps finding the problem easier

**Comment by GeraltOfMurlocs** [comment]
1.  Those that work (meaning they stay open) are auto-fight and missions. The rest insta close after inputting and pressing enter.
2.  Intially, I tried it on roxa, and then exura and alpha
3. Practically instantly
4. I have downloaded several copies of these files as well as reinstalled python
5. I meant discord bot. My teammate was able to get it to work, and while thats running I can use commands and tell it what to do. Really weird that the 'bot' file works but nothing else. 
6. I moved the eSim folder from scriptmaster to my desktop (I do not think this is significant). 
7. I use PC.

![image](https://user-images.githubusercontent.com/84540920/119059329-c38ffc80-b9d8-11eb-9342-8a880856bb4c.png)
![image](https://user-images.githubusercontent.com/84540920/119059341-c7bc1a00-b9d8-11eb-91aa-219a58037b9d.png)

**Comment by Random-guy-on-internet** [comment]
unfortunately, i was not able to reproduce the same error.
![Screenshot_6](https://user-images.githubusercontent.com/66680456/119079377-3ca94700-ba0d-11eb-95b2-6cab47c5a9d7.jpg)

------
Here is what i suggest you to do:

1. Download scripts again from this link : [Download Link](https://github.com/e-sim-python/scripts/archive/refs/heads/master.zip) , unzip it, first give it another try to see if its still faulty, if it failed, go further steps.
2. Uninstall Python from your pc, reboot your pc first, after reboot Download [python 3.8.8 from official page](https://www.python.org/downloads/release/python-388/)
[ Here is Download link for your convenience ](https://www.python.org/ftp/python/3.8.8/python-3.8.8.exe)

install python 3.8.8 and make sure to tick **Add Python 3.8.8 to path** when installing.
after its installed, reboot again.

Then after rebooting, open command prompt (cmd), and type: `python --version`
if you don't skip any steps, you should see something like `Python 3.8.8`

Then in the same CMD window, type this: `pip install lxml aiohttp`

if you have the packages, it will output something like this:
![Screenshot_3](https://user-images.githubusercontent.com/66680456/119078469-81cc7980-ba0b-11eb-8dfe-0a32922a6e56.jpg)

**and if you don't have them, it will be like this:**

![Screenshot_4](https://user-images.githubusercontent.com/66680456/119078788-1df68080-ba0c-11eb-9ad7-b66d8b266608.jpg)

3. Now head back to the script folder and run the scripts again to see if it fixed the problem.
4. if last step failed, you can open the script files with python interpreter and give it a try.
to do so, right-click on the script file, and select `Edit with IDLE > Edit with IDLE 3.8 (32 bit)`.
This will open the script file in python interpreter and you can run Scripts with pressing F5 Key on your keyboard or go to the run Menu in python interpreter and click on Run Module.
![Screenshot_5](https://user-images.githubusercontent.com/66680456/119079248-f9e76f00-ba0c-11eb-8c27-b14a2bbfc964.jpg)

-----
Let Me know how it goes!

Good Luck
