### ISSUE TITLE
Sending commands in discord

### ISSUE THREAD

**Issue by SH4LT1S** [e-sim-python/scripts#34]
How do I do it?

**Comment by Random-guy-on-internet** [comment]
Read these issues please, but the short version is, first you set up your secret key, after running the discord bot, you make a channel with the same server name as u want to use the bot with, then you can send commands like other bots, use **.help** for more details

https://github.com/e-sim-python/scripts/issues/7
https://github.com/e-sim-python/scripts/issues/8
https://github.com/e-sim-python/scripts/issues/11

**Comment by SH4LT1S** [comment]
> Read these issues please, but the short version ....

Thanks You! Another quick question: Lets say I put 2 discord bots for two accounts in IG server (in #server aswell), how do I send command for specific acc? @mention?

**Comment by SH4LT1S** [comment]
![esim](https://user-images.githubusercontent.com/56916200/119252856-1e7f4a80-bbb7-11eb-9355-e480a4aad476.gif)
Also this.
First is _.work_
Second is _.work nickname_ and it crashes without working

**Comment by Random-guy-on-internet** [comment]
so far so good.

now you need to configure account(s) first, open up one of the scripts manually, add the account(s) for the server(s) u want OR edit the `login_details.csv` file if you know what you are doing.

after configuring servers, accounts and useragent strings, run the bot, go to discord and try commands like this:

lets assume the account username in game is `Railman` and the server is `Secura`.

to work with `Railman` account, you will send `.work Railman` in discord and within `#secura` channel.

**keep in mind that if your username has 2+ words with space in between and nickname is not the last argument (like in .fight command ), you need to send it within quotes like this:**

ingame username: The Mad Man

send it in discord like this: `.fight "The Mad Man" link side wep etc....`

**Comment by SH4LT1S** [comment]
I did that but no matter what I type, work, fight, shout, it crashes. I made new clean csv, but it didnt help

**Comment by Random-guy-on-internet** [comment]
okay, open the `bot.py` in python interpreter with right-clicking on the file and selecting `Edit with IDLE > Edit with IDLE ` then run the bot by pressing F5 Key on the keyboard, then run the command that causes the crash, then send me the error screenshot.

**Comment by SH4LT1S** [comment]
NVM, fixed it by using cookies from firefox, not edge
