### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ArtiomkaLenkas** [e-sim-python/scripts#35]
Fight and autofight dont work. Nothing happens.
![notworkling](https://user-images.githubusercontent.com/84674724/119266758-e79e3a00-bba0-11eb-88cb-32353319a842.png)

**Comment by Random-guy-on-internet** [comment]
Hi @ArtiomkaLenkas 

Open the `Help_function` folder, delete the `cookies.txt` file, and test the scripts again, it will most likely fix it.

**Comment by ArtiomkaLenkas** [comment]
Not helped

**Comment by Random-guy-on-internet** [comment]
Okay, it is working for me without any problems:

![Screenshot_1](https://user-images.githubusercontent.com/66680456/119310710-640a4900-bc85-11eb-8126-53d3b2089ebb.jpg)

Maybe Download the scripts again [download link](https://github.com/e-sim-python/scripts/archive/refs/heads/master.zip)
and give it another try, if that didn't solve the problem, maybe the account is banned or you have internet connection issues.

**Comment by ArtiomkaLenkas** [comment]
Still no :/

**Comment by Random-guy-on-internet** [comment]
------
Here is what I suggest you do:

1. Download scripts again from this link : [Download Link](https://github.com/e-sim-python/scripts/archive/refs/heads/master.zip), unzip it, first give it another try to see if it's still faulty, if it failed, go further steps.
2. Uninstall Python from your pc, reboot your pc first, after reboot Download [python 3.8.8 from official page](https://www.python.org/downloads/release/python-388/)
[ Here is the Download link for your convenience ](https://www.python.org/ftp/python/3.8.8/python-3.8.8.exe)

install python 3.8.8 and make sure to tick **Add Python 3.8.8 to path** when installing.
after its installed, reboot again.

Then after rebooting, open command prompt (cmd), and type: `python --version`
if you don't skip any steps, you should see something like `Python 3.8.8`

Then in the same CMD window, type this: `pip install lxml aiohttp`

if you have the packages, it will output something like this:
![Screenshot_3](https://user-images.githubusercontent.com/66680456/119078469-81cc7980-ba0b-11eb-8dfe-0a32922a6e56.jpg)

**and if you don't have them, it will be like this:**

![Screenshot_4](https://user-images.githubusercontent.com/66680456/119078788-1df68080-ba0c-11eb-9ad7-b66d8b266608.jpg)

3. Now head back to the script folder and run the scripts again to see if it fixed the problem.
4. if the last step failed, you can open the script files with python interpreter and give it a try.
to do so, right-click on the script file, and select `Edit with IDLE > Edit with IDLE 3.8 (32 bit)`.
This will open the script file in the python interpreter and you can run Scripts by pressing the F5 Key on your keyboard or go to the run menu in the python interpreter and click on Run Module.
![Screenshot_5](https://user-images.githubusercontent.com/66680456/119079248-f9e76f00-ba0c-11eb-8c27-b14a2bbfc964.jpg)

-----
Let Me know how it goes!

Good Luck

**Comment by ArtiomkaLenkas** [comment]
![Capture](https://user-images.githubusercontent.com/84674724/119342024-56cf6900-bc49-11eb-90c5-3e27972e7faf.PNG)

**Comment by Random-guy-on-internet** [comment]
you have connection problems, maybe test the scripts on another network or connect to a VPN and give it a try.

**Comment by ArtiomkaLenkas** [comment]
is it possible to run this as a docker container?

**Comment by Random-guy-on-internet** [comment]
honestly, I don't know how docker works or what it is for that matter to comment on that.
