### ISSUE TITLE
Discord bot issue

### ISSUE THREAD

**Issue by Poropropo** [e-sim-python/scripts#7]
After trying so hard to fix most of the errors i got, i endedup getting this one, which i don't know how to fix it: 
![image](https://user-images.githubusercontent.com/75151771/100492926-5ded4280-3110-11eb-82e8-9e8c2da820d5.png)

(this happens when i have to put the bot token)

**Comment by Random-guy-on-internet** [comment]
Hello, there is a LoginFailure Error in there which means either you didnt do it right or the token is invalid so,
assuming that you successfully grabbed your bot token from discord's developers portal and its valid, 
# here is what you need to do:

 - open [bot.py](https://github.com/e-sim-python/scripts/blob/master/bot.py) file in python editor.

 - in [this line ](https://github.com/e-sim-python/scripts/blob/dd9db8eedb08c1629ff68b9efce0722c894a5ec0/bot.py#L14), you need to replace like so:

```python
YOUR_SECRET_TOKEN = input("Your discord token (help - https://discordpy.readthedocs.io/en/latest/discord.html): ")
````
To this: 
```python
YOUR_SECRET_TOKEN = "Your_discord_token"
````
remember your discord token has to be between two `"`(Quote) to work.

for example if your bot token is something like `NzQxzQxNDI4NjzQxNDI4NjzQxNDIzQxNDI4NjESHSndVG0` ,
`YOUR_SECRET_TOKEN` will be like this:

```python
YOUR_SECRET_TOKEN = "NzQxzQxNDI4NjzQxNDI4NjzQxNDIzQxNDI4NjESHSndVG0"
````
So edit the line as i explained and save the file.

Let us know how it goes.

Good Luck!

**Comment by Poropropo** [comment]
After editing the file i still getting the same errors

**Comment by Poropropo** [comment]
I just realized i was copying a different bot token, now it worked.
 Thanks for the help <3


But i have another question, 
![image](https://user-images.githubusercontent.com/75151771/100548903-85e2c000-324e-11eb-9b29-6dfa95adf659.png)

how does this work?

**Comment by Random-guy-on-internet** [comment]
Well, if the documentation/ Help notes are not clear enough, you can always come to this repository and read the codes for each part you want.

Here is a tip to find each code sections:

for example in [bot.py](https://github.com/e-sim-python/scripts/blob/master/bot.py) file you like to know how `login(server)` function works.

1. you open [bot.py](https://github.com/e-sim-python/scripts/blob/master/bot.py) file in here (github).
2. search for `login(server)` by pressing Ctrl + F.
3. if you click on the highlighted text(`login(server)`) a pop up opens like so : [SCREENSHOT](http://prntscr.com/vti4xt)
4. by clicking on the code line in pop up, the actual code for the function will open and you can check out what it does.
-----
Now assuming you already know this, and you want to know what `!Login` command does,
if you are invoking some commands like `!w` and it doesnt work ingame, maybe the cookies expired and you need to refresh them manually, you can do so by invoking the `!Login` command, the `!Login` command will log you in the server and stores the session for later use of bot.

**Comment by e-sim-python** [comment]
Just a quick note:
The commands are case **in**sensitive, which means `.Login` = `.login` (the current prefix is `.`).

Also, try `.help login` (the same goes for the rest of the commands in question).
