### ISSUE TITLE
bot

### ISSUE THREAD

**Issue by Dol0s** [e-sim-python/scripts#8]
Nice work on the scripts. when running the bot I get the error 

![image](https://user-images.githubusercontent.com/74241000/101245509-b2468280-370d-11eb-8acd-f40ea268b5d5.png)
it returns test for everything but does not carry out the requests. >Could you help me

**Comment by Random-guy-on-internet** [comment]
Hi,
1. first, check if the name of the channel you are running the command is matching with the server you are trying to use the account with, for example **if its a secura account**, the **name of channel should be secura**, if this didnt help, move to second option.

2. in `Help_functions` folder, look for `login_details.csv` file, open in a text editor ( [np++ ](https://notepad-plus-plus.org/downloads/)perhaps or the usual windows notepad works as well ) maybe you saved a `'test'` account before.

if thats the case, simply delete the `login_details.csv` file and try the bot again.

also providing more detail is appreciated. (like what command did you use, etc)

**Comment by Dol0s** [comment]
I hadn't the channel set up. Thanks :)
